export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_START = "FETCH_EVENTS_START";
export const FETCH_SINGLE_EVENT_FAILURE = "FETCH_SINGLE_EVENT_FAILURE";
export const FETCH_SINGLE_EVENT_SUCCESS="FETCH_SINGLE_EVENT_SUCCESS";
export const INCREMENT_OFFSET = "INCREMENT_OFFSET";
export const RESET_EVENTS_LIST =   "RESET_EVENTS_LIST";
export const FETCH_FILTERED_EVENTS_SUCCESS = "FETCH_FILTERED_EVENTS_SUCCESS";